### PR TITLE
fix: create sync task by 'GET /:fullname/-/:filenameWithVersion.tgz'

### PR DESCRIPTION
**Pull request by hezhengxu2018**
used by pnpm project with lock

closes https://github.com/cnpm/cnpmcore/issues/525

### CODE REVIEW

**Comment by fengmk2** [comment]
@hezhengxu2018 补充一个对应的单测

**Comment by fengmk2** [comment]
rebase 一下？带了已经合并的代码。

**Comment by hezhengxu2018** [comment]
好了

**Review by fengmk2 — APPROVED** [review]
+1

**Pull request merged**
