### PR TITLE
🐛 FIX: skia-canvas should use NodePreGypBinary

### PR DESCRIPTION
**Pull request by fengmk2**
closes https://github.com/cnpm/cnpmcore/pull/258

### CODE REVIEW

**Comment by Beace** [comment]
貌似还是没成功 https://r.cnpmjs.org/binary.html?path=skia-canvas/

**Comment by fengmk2** [comment]
> 貌似还是没成功 https://r.cnpmjs.org/binary.html?path=skia-canvas/

https://r.cnpmjs.org/-/binary/skia-canvas/v0.9.30/linux-arm64-napi-v6-glibc.tar.gz 文件成功了，目录不行，我再看看。

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmcore/pull/260

**Comment by fengmk2** [comment]
@Beace done https://r.cnpmjs.org/binary.html?path=skia-canvas/v0.9.30/ 
我去同步一下 npmmirror

**Pull request merged**
